### ISSUE TITLE
Add other obfuscators?

### ISSUE THREAD

**Issue by SelfMadeSystem** [GenericException/SkidSuite#4]
https://branchlock.net/
https://mdma.dev/
https://jnic.dev/
https://binclub.dev/binscure

**Comment by GenericException** [comment]
These are all paid, and I'm not gonna dish out money. If anyone has these and is willing to churn out a few samples sort of like how the other obfuscators are demo'd that would be cool.

Plus: https://github.com/superblaubeere27/obfuscator - Was asked to do before but forgot

**Comment by GenericException** [comment]
> mdma.dev

Seems to be defunct now

**Comment by GenericException** [comment]
Added links, but wont be adding samples myself as mentioned before.
