### ISSUE TITLE
add more obfuscation samples

### ISSUE THREAD

**Issue by JohnShiozo** [GenericException/SkidSuite#5]
[samples.zip](https://github.com/GenericException/SkidSuite/files/6368357/samples.zip)
contents:
binscure samples, Jobf samples and ClassGuard sample
#1

**Comment by GenericException** [comment]
I would argue that `ClassGuard ` is more of a packer than an obfuscator. Its just a C classloader that can be dumped at runtime.

Will add the others though.

**Comment by GenericException** [comment]
Thanks for the samples, added

**Comment by JohnShiozo** [comment]
i enabled jobf crasher transformer it should add crash code or its just broken
